config/routes.rb
Rails.application.routes.draw do
  resources :galleries
  #devise_for :users
  devise_for :users, :controllers => { registrations: "users/registrations", sessions: "users/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home_pages#index"
  resources :contacts
  resources :github_pages
  resources :tweets
  resources :blog_posts, only: [:index, :create, :new, :show]
  resources :blog_posts do
    resources :comments
  end
  resources :blog_posts do
    resources :likes
  end

  get "/admin" => "home_pages#make_admin"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog_post
  belongs_to :user

  validate :validate_comment
  private

  def validate_comment
    if  self.comment.strip==""
      errors.add(:comment,"comment can't be empty!")
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @blog_post = BlogPost.find(params[:blog_post_id])
    @comment = @blog_post.comments.new(comment_params)
    @comment.user_id = current_user.id
    @comment.user_name=current_user.email
    if @comment.save
      CommentMailer.send_comment(@comment).deliver_later
      redirect_to blog_post_path(@blog_post)
    else
      flash[:danger] = @comment.errors.values.join(', ')
      redirect_to blog_post_path(@blog_post)
    end
  end
  def destroy
   @blog_post=BlogPost.find(params[:blog_post_id])
   @comment=@blog_post.comments.find(params[:id])
   @comment.destroy
   redirect_to blog_post_path(@blog_post)
  end
  private

  def comment_params
    params[:comment].permit(:comment)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="cm-del">
<div style="display:flex"><%= markdown comment.comment%>
<%if user_signed_in?%>
<% if current_user.id==comment.user_id%>
<div class="del-option">
<%= link_to(blog_post_comment_path(comment.blog_post,comment), method: :delete)  do %>
       <%= inline_svg "delete.svg" , class: "svg-delete "%>
     <% end %>

</div>
<%end%>
<%end%></div>
<div><div class="commenter-name">Commented by <strong><%=comment.user_name%></strong></div></div>

</div>

app/views/comments/_new.html.erb
<div class="comm-form">
<%= form_for([@blog_post, @blog_post.comments.build]) do |f| %>
  <div class="form-group size">


    <%= f.text_area :comment, class: "form-control", rows:2, placeholder: "leave a comment"%>
    <br/>
    <%= f.submit  "Comment", class: "btn btn-primary"%>
  </div>
<% end %>
<p>You can use Markdown Styles for commenting.<a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Sheet here!</a></p>
</div>