config/routes.rb
Rails.application.routes.draw do
  resources :galleries
  #devise_for :users
  devise_for :users, :controllers => { registrations: "users/registrations", sessions: "users/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home_pages#index"
  resources :contacts
  resources :github_pages
  resources :tweets
  resources :blog_posts, only: [:index, :create, :new, :show]
  resources :blog_posts do
    resources :comments
  end
  resources :blog_posts do
    resources :likes
  end

  get "/admin" => "home_pages#make_admin"
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  after_validation :set_slug, only: [:create, :update]

  def to_param
    "#{id}-#{slug}"
  end

  #validates :title, presence: true
  #validates :content, presence: true
  validate :validate_title_and_content

  private

  def validate_title_and_content
    if self.title.strip == ""
      errors.add(:blog_post, "Are you trying to write Title less content!")
    elsif self.title.length < 10
      errors.add(:blog_post, "Title must be minimum of 10 charcters!")
    elsif self.content.strip == ""
      errors.add(:blog_post, "Are  you trying to submit content less title..!")
    elsif self.content.length < 100
      errors.add(:blog_post, "Write a minimum content of 100 charcters..!")
    end
  end

  def set_slug
    self.slug = title.to_s.parameterize
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :authenticate_user!, :except => [:show, :index]

  def index
    @blog_posts = BlogPost.order("created_at DESC").paginate(page: params[:page], per_page: 4)
  end

  def new
    unless current_user.admin?
      flash[:danger] = "You are not allowed to access this page."
      redirect_to blog_posts_path
    end
    @blog_post = BlogPost.new
  end

  def create
    unless current_user.admin?
      flash[:danger] = "You are not allowed to access this page."
      redirect_to blog_posts_path
    end
    @blog_post = BlogPost.new(blogpost_params)
    if @blog_post.save
      redirect_to action: "index"
    else
      flash[:danger] = @blog_post.errors.values.join(", ")
      redirect_to action: "new"
    end
  end

  def update
    unless current_user.admin?
      flash[:danger] = "You are not allowed to access this page."
      redirect_to blog_posts_path
    end
    @blog_post = BlogPost.find(params[:id])
    if @blog_post.update(blogpost_params)
      redirect_to @blog_post
    else
      render "edit"
    end
  end

  def edit
    unless current_user.admin?
      flash[:danger] = "You are not allowed to access this page."
      redirect_to blog_posts_path
    end
    @blog_post = BlogPost.find(params[:id])
  end

  def show
    @blog_post = BlogPost.find(params[:id])
  end

  def destroy
    @blog_post = BlogPost.find(params[:id])
    @blog_post.destroy
    redirect_to action: "index"
  end

  private

  def blogpost_params
    params[:blog_post].permit(:title, :content)
  end

end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper

end

app/views/blog_posts/edit.html.erb
<section class="cp-page">
<button type="button" class="btn btn-outline-primary"><a href="<%=blog_posts_path%>">Back To Blog</a></button>
<h2 class="hd-hd">Edit the Post</h2>
<div class="hr-line"></div>
<%= form_for(@blog_post) do |f| %>
  <div class="form-group size">
    <label>Title</label>
    <%= f.text_field :title, class: "form-control", placeholder: @blog_post.title%>
    <br/>
      <label>Content</label>
    <%= f.text_area :content, class: "form-control", rows:10, placeholder: @blog_post.content%>
    <br/>
    <%= f.submit text: "Update", class: "btn btn-success"%>
  </div>
<% end %>
</section>

app/views/blog_posts/index.html.erb
<section class="blog-page">
<div>
<div class="head">
<div class="hd-style2">Vamsi Bellam</div>
<div class="t-links">
<div class="bgpage-links"><a href="<%=root_path%>">Home</a></div>
<!--
<div class="bgpage-links"><a href="#">About</a></div> -->
<% if user_signed_in?%>
<% if current_user.admin?%>
<div class="bgpage-links"><a href="<%= new_blog_post_path%>">Create Post</a></div>
<%end%>
<%end%>
<span class="bgpage-links">
    <% if user_signed_in? %>

      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
     <!-- <span class="login-name"> Logged in as <strong><%= current_user.email %></strong> <span> -->
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
  </span>
  <div class="hd-style3">Vamsi Bellam</div>
</div>
</div>
<div class="hr-line2"></div>
</div>

<h2 class="hd-style">My Blog Posts </h2>

<!--<div class="hr-line"></div>-->

<div class="total-posts">

<% @blog_posts.each do |post| %>
<div>
  <div class="single-post" >
    <p><span class="post-day"><%=post.created_at.to_date.strftime("%d %B, %Y") %></span></p>
  <div class="post-title"><%= link_to post.title, blog_post_path(post) %>


  </div>
  <div class="post-det">
  <p class="likes-count"><%= post.likes.count %></p>
  <%if user_signed_in?%>
  <% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>
  <%end%>
  <% if pre_like %>
      <%= link_to(blog_post_like_path(post,pre_like), method: :delete)  do %>
       <%= inline_svg "love2.svg" , class: "svg-model-filled"%>
     <% end %>
  <% else %>
     <%= link_to(blog_post_likes_path(post), method: :post)  do %>
       <%= inline_svg "like.svg" , class: "svg-model"%>
     <% end %>
  <% end %>



   <!--
  <div class=p-comments><%=post.comments.count%><%=fa_icon "comments" ,class:"comment-gap"%> </div>  -->
    <div class=p-comments><%=post.comments.count%> <%= inline_svg "comment-white-oval-bubble.svg" , class: "svg-comment"%> </div>
</div>
  </div>
  </div>
<% end %>

<div class="pagination-center">
<%= will_paginate @blog_posts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer  %>
</div>
</div>

</section>

app/views/blog_posts/new.html.erb
<section class="cp-page">
<button type="button" class="btn btn-outline-primary"><a href="<%=blog_posts_path%>">Back To Blog</a></button>

<h2 class="hd-hd">Create a New Post</h2>
<div class="hr-line"></div>
<%= form_for(@blog_post) do |f| %>
  <div class="form-group size">
    <label>Title</label>
    <%= f.text_field :title, class: "form-control", placeholder: "Title for post"%>
    <br/>
      <label>Content</label>
    <%= f.text_area :content, class: "form-control", rows:10, placeholder: "write the content"%>
    <br/>
    <%= f.submit text: "Post", class: "btn btn-success"%>
  </div>
<% end %>
</section>

app/views/blog_posts/show.html.erb
<section class="full-page">
<div class="content-1">
<div>
<div class="head">

<div class="hd-style2">Vamsi Bellam</div>
<div class="t-links">
<div class="bgpage-links"><a href="<%=blog_posts_path%>">BlogPosts</a></div>
<%if user_signed_in?%>
<% if current_user.admin?%>
<div class="bgpage-links"><a href="<%=edit_blog_post_path%>">Edit Post</a></div>
<div class="bgpage-links"><%= link_to 'Delete Post', blog_post_path, method: :delete, data:{confirm: "Are you sure to delete post?"} %></div>
<%end%>
<%else%>
<%end%>
<div class="hd-style3">Vamsi Bellam</div>
</div>
</div>
</div>
<div class="hr-line2">
</div>
<h1><%=@blog_post.title%></h1>

<div class="content-size">
<%=markdown(@blog_post.content)%>
</div>
</div>
<div class="comment-box">
<label style="padding-top:20px"><strong>Comments</strong></label>
<div class="comment-details">
<%= render @blog_post.comments %>
</div>
<%if user_signed_in?%>
<%= render 'comments/new'%>
<%end%>
</div>
</section>