config/routes.rb
Rails.application.routes.draw do
  resources :galleries
  #devise_for :users
  devise_for :users, :controllers => { registrations: "users/registrations", sessions: "users/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home_pages#index"
  resources :contacts
  resources :github_pages
  resources :tweets
  resources :blog_posts, only: [:index, :create, :new, :show]
  resources :blog_posts do
    resources :comments
  end
  resources :blog_posts do
    resources :likes
  end

  get "/admin" => "home_pages#make_admin"
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
  def index
  end

  def make_admin
    user = User.first
    user.admin = true
    user.save!
    flash[:notice] = "updated"
    redirect_to "/"
  end
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/views/home_pages/index.html.erb
<div id="bg-img">
<div id="bg-imglayer">
<header>

<nav class="my-navbar">

<div id="myNav" class="overlay">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <div class="overlay-content">
    <a href="<%= github_pages_path%>">My Github</a>
    <a href="<%= tweets_path%>">My Tweets</a>
    <a href="<%= new_contact_path%>">Contact</a>
    <a href="<%=blog_posts_path%>">My Blog</a>
  </div>
</div>
<span class="mb-browser" style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; </span>
<ul>
<!--
<li>
<a href="#">Home</a>
</li>
<li>
<a href="#">About</a>
</li>
<li>
<a href="/admin">Make admin</a>
</li> -->
<li>
<a href="<%= github_pages_path%>">My Github</a>
</li>
<li>
<a href="<%= tweets_path%>">My Tweets</a>
</li>

<li>
<a href="<%= new_contact_path%>">Contact</a>
</li>
<li>
<a href="<%=blog_posts_path%>">My Blog</a>
</li>
</ul>
</nav>
</header>
<!--<div class="line">
</div> -->
<div class="sd-sd">
<div class="my-photo">
</div>
<div class="my-content">
<h3>Hi, This is Vamsi <span style="color:tomato">Bellam.</span></h3>

<span class="large">I'am a</span><span style="color:white" id="typed-sample">
</span>
<h4></h4>
<div class="same-line">
<%= link_to "https://twitter.com/Bellam_3415?s=03" ,target: :_blank do %>
<%=fa_stacked_icon "twitter", base: "square-o", class: "sl-tw"%>
<% end %>
<%= link_to "https://m.facebook.com/vamsikrishna.bellam.9" ,target: :_blank do %>
<%=fa_stacked_icon "facebook", base: "square-o",class: "sl-fb"%>
<% end %>
<%= link_to "https://www.instagram.com/vamsi.bellam/" ,target: :_blank do %>
<%=fa_stacked_icon "instagram", base: "square-o", class: "sl-in"%>
<% end %>
<%= link_to "https://github.com/vamsikri-hash" ,target: :_blank do %>
<%=fa_stacked_icon "github", base: "square-o", class:"sl-gh"%>
<% end %>
<%= link_to "https://reddit.com/user/bellam_vk/" ,target: :_blank do %>
<%=fa_stacked_icon "reddit", base: "square-o", class:"sl-rt"%>
<% end %>
</div>
</div>
</div>
</div>
</div>


<script>
function openNav() {
  document.getElementById("myNav").style.width = "100%";
}

function closeNav() {
  document.getElementById("myNav").style.width = "0%";
}
</script>