config/routes.rb
Rails.application.routes.draw do
  resources :galleries
  #devise_for :users
  devise_for :users, :controllers => { registrations: "users/registrations", sessions: "users/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home_pages#index"
  resources :contacts
  resources :github_pages
  resources :tweets
  resources :blog_posts, only: [:index, :create, :new, :show]
  resources :blog_posts do
    resources :comments
  end
  resources :blog_posts do
    resources :likes
  end

  get "/admin" => "home_pages#make_admin"
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  has_one_attached :image
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
  end

  # GET /galleries/1/edit
  def edit
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: "Gallery was successfully created." }
        format.json { render :show, status: :created, location: @gallery }
      else
        format.html { render :new }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: "Gallery was successfully updated." }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_url, notice: "Gallery was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_gallery
    @gallery = Gallery.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def gallery_params
    params.require(:gallery).permit(:image, :description)
  end
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/galleries/_form.html.erb
<%= form_with(model: gallery, local: true) do |form| %>
  <% if gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% gallery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <div class="form-group size  gal-form">
    <label>Title</label>
    <%= form.text_field :description, class: "form-control", placeholder: "Title for post"%>
    <br/>
    <label>Image</label>
    <%= form.file_field :image, class: "form-control pd-pd"%>

     <div class="actions">
    <%= form.submit "Add Image", class: "btn btn-success"%>
    <%= link_to 'Back', galleries_path , class:"btn btn-primary"%>
  </div>
  </div>


<% end %>

app/views/galleries/edit.html.erb
<h1 class="my-gal">Edit Your Photo-Post</h1>

<%= render 'form', gallery: @gallery %>

app/views/galleries/index.html.erb
<p id="notice"><%= notice %></p>

<div class="gal-head">
<h1 class="my-gal">My Photo Gallery</h1>
<%= link_to 'Add New Photo', new_gallery_path,class:"new-photo" %>
</div>

    <div class="fit">
    <% @galleries.each do |gallery| %>
     <div>
     <div class="img-cont">
      <%= image_tag gallery.image, class: "basic-length" %>
      <p class= "card-title good-des"><%= gallery.description%></p>

     </div>
      <div>


        <td><%= link_to 'Edit', edit_gallery_path(gallery) %></td> |
        <td><%= link_to 'Destroy', gallery, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </div>
     </div>
    <% end %>

    </div>


<br>

app/views/galleries/new.html.erb
<h1 class="my-gal"> Add Your New Photo</h1>

<%= render 'form', gallery: @gallery %>

app/views/galleries/show.html.erb
<p id="notice"><%= notice %></p>
 <div class="images-content">
 <%= image_tag @gallery.image, class: "basic-length"%>
 <%= @gallery.description%>
 </div>
<%= link_to 'Edit', edit_gallery_path(@gallery) %> |
<%= link_to 'Back', galleries_path %>